version: '2'

volumes:
  mongo-vol: {}

services:

  mongo:
    image: mongo
    ports:
       - "27017:27017"
    volumes:
      - mongo-vol:/data/db
    container_name: mongoCluster
    # environment:
    #   - MONGODB_REPLICA_SET_MODE=primary

  master:
    image: sequenceiq/spark:1.4.0
    hostname: master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    expose: 
      - "7077" 
    # environment:
    #   - INIT_DAEMON_STEP=setup_spark
      # - "constraint:node==<yourmasternode>"
    links:
          - mongo
    restart : always
    command: bash /usr/local/spark/sbin/start-master.sh && ping localhost > /dev/null

  spark-worker-1:
    image: sequenceiq/spark:1.4.0
    container_name: spark-slave
    # depends_on:
    #   - master
    # ports:
    #   - "8081:8081"
    # environment:
      # - "SPARK_MASTER=spark://spark-master:7077"
      # - "constraint:node==<yourmasternode>"
    links:
          - mongo
          - master:master
    expose: 
      - "8081"
    restart : always
    command: bash /usr/local/spark/sbin/start-slave.sh spark://master:7077 && ping localhost > /dev/null
      # - spark/sbin/start-slave.sh spark://master:7077



